version: "3"

services:
    web:
        build: .
        command: python3 tun.py
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
